### ISSUE TITLE
No user feedback to see if credentials have been saved.

### ISSUE THREAD

**Issue by WillMayger** [BeauAgst/gforces-assistant#1]
No user feedback to see if credentials have been saved.
Discussed about having the toggle only switchable to on if the user has entered credentials

**Comment by metacurb** [comment]
This will be fixed as part of 7bcfaa163a24f974668d567c444c458eb8208bdc. A modal now appears if login fails and auto-login is set to on.

![image](https://user-images.githubusercontent.com/10343831/31943122-923424e0-b8bf-11e7-9679-23a2327fb18b.png)
