### ISSUE TITLE
Jira Sub-task Organiser

### ISSUE THREAD

**Issue by nuno-barros** [BeauAgst/gforces-assistant#2]
Can we have the sub-task with different color when it has a label?

For example, every sub-task that has a label, can we have the background in grey/orange? 
This should only be applied if the sub-task is "Queued" or "Not Started"

Also would it be possible to have the labels on a title tag?

**Comment by metacurb** [comment]
@nuno-barros what if each label has an icon of some description, indicating that the sub-task has labels assigned to it? And then from there you hover the issue and shows the labels inside the title tag?

**Comment by nuno-barros** [comment]
Perfect


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: BeauAgst <notifications@github.com> Date: 26/10/2017  16:08  (GMT+00:00) To: BeauAgst/gforces-assistant <gforces-assistant@noreply.github.com> Cc: nuno-barros <nuno.barros@gforces.co.uk>, Mention <mention@noreply.github.com> Subject: Re: [BeauAgst/gforces-assistant] Jira Sub-task Organiser (#2) 
@nuno-barros what if each label has an icon of some description, indicating that the sub-task has labels assigned to it? And then from there you hover the issue and shows the labels inside the title tag?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BeauAgst/gforces-assistant","title":"BeauAgst/gforces-assistant","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BeauAgst/gforces-assistant"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BeauAgst in #2: @nuno-barros what if each label has an icon of some description, indicating that the sub-task has labels assigned to it? And then from there you hover the issue and shows the labels inside the title tag?"}],"action":{"name":"View Issue","url":"https://github.com/BeauAgst/gforces-assistant/issues/2#issuecomment-339697221"}}}

**Comment by metacurb** [comment]
Icons have been added alongside each issue in e56fa36454fc57f15ead810bbfad12e132285994. Hovering an issue will show those labels in the title attribute 

![image](https://user-images.githubusercontent.com/10343831/32093380-f755a4e4-baf3-11e7-86a0-b4aa4d3602f2.png)
