### ISSUE TITLE
Dynamic Elements - UX enhancements

### ISSUE THREAD

**Issue by BradleyArnott** [BeauAgst/gforces-assistant#3]
# Dynamic Elements - Improvements
After discovering a site with many child pages in dynamic elements it is difficult to select between them all, as seen below in the screenshot
![chrome_2017-10-25_09-00-01](https://user-images.githubusercontent.com/8159761/31987319-5bd0eab0-b963-11e7-815e-5eb488662758.png)

It would be good if we could have a similar integration as per tag management where we can auto select or tag certain pages which are easily done, or even to have a search aspect again.
![chrome_2017-10-25_09-02-47](https://user-images.githubusercontent.com/8159761/31987323-5da498c8-b963-11e7-9c0a-48a42b8bb95d.png)

Overall just some general improvements

**Comment by metacurb** [comment]
It looks like I'll be able to add a search in, but only for the pages section. So you'd still have to select the franchise and section first. Would that still be useful?

**Comment by metacurb** [comment]
"Add all" and "Remove all" buttons added in e56fa36454fc57f15ead810bbfad12e132285994

![image](https://user-images.githubusercontent.com/10343831/32839750-58b1f97c-ca0d-11e7-9547-dc3910f7618b.png)
